FROM   ubuntu:18.04
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install systemd
RUN apt-get -y install openssh-client
RUN apt-get -y install openssh-server
RUN apt-get -y install ansible

# We need this since we want to login to other via ssh using pw
RUN apt-get -y install sshpass

#### For dev purposes ####
# Set root as pw for root user
RUN echo "root:root" | chpasswd
RUN apt-get -y install nano
RUN apt-get -y install curl
RUN apt-get -y install iputils-ping

# Place and run our specific start script
COPY ./start-controller /bin/start

CMD ["/bin/start"]